import type { CatalogItem } from "@/features/navigation/types";

export const problemCatalog: CatalogItem[] = [
  {
    id: "grid-bfs",
    group: "Graph",
    title: "Problem Trace: Grid BFS",
    description: "Grid 문제에서 BFS 탐색, 가지치기, 경로 복원을 step 단위로 검증합니다.",
    href: "/problems/grid-bfs",
    ctaLabel: "Grid BFS 시작",
    accentClass: "bg-indigo-600 hover:bg-indigo-700",
  },
  {
    id: "grid-dfs",
    group: "Graph",
    title: "Problem Trace: Grid DFS",
    description: "Grid 문제에서 DFS 탐색, 가지치기, 경로 복원을 step 단위로 검증합니다.",
    href: "/problems/grid-dfs",
    ctaLabel: "Grid DFS 시작",
    accentClass: "bg-violet-600 hover:bg-violet-700",
  },
  {
    id: "dp-recurrence",
    group: "DP",
    title: "Problem Trace: DP Recurrence",
    description: "점화식을 직접 입력해 DP 테이블 계산 과정을 step 단위로 시각화합니다.",
    href: "/problems/dp-recurrence",
    ctaLabel: "DP Recurrence 시작",
    accentClass: "bg-cyan-600 hover:bg-cyan-700",
  },
  {
    id: "dp-knapsack",
    group: "DP",
    title: "Problem Trace: 0/1 Knapsack DP",
    description: "0/1 Knapsack 테이블 계산과 선택 복원을 step 단위로 확인합니다.",
    href: "/problems/dp-knapsack",
    ctaLabel: "Knapsack 시작",
    accentClass: "bg-teal-600 hover:bg-teal-700",
  },
  {
    id: "dp-grid-min-path",
    group: "DP",
    title: "Problem Trace: Grid Min Path Sum DP",
    description: "최소 경로 합 DP 테이블 계산과 경로 복원을 step 단위로 시각화합니다.",
    href: "/problems/dp-grid-min-path",
    ctaLabel: "Grid Min Path 시작",
    accentClass: "bg-lime-600 hover:bg-lime-700",
  },
  {
    id: "backtracking-generic",
    group: "Backtracking",
    title: "Problem Trace: Backtracking Generic",
    description: "제약식/목표식을 직접 입력해 백트래킹 탐색 과정을 step 단위로 확인합니다.",
    href: "/problems/backtracking-generic",
    ctaLabel: "Backtracking Generic 시작",
    accentClass: "bg-orange-600 hover:bg-orange-700",
  },
  {
    id: "backtracking-n-queens",
    group: "Backtracking",
    title: "Problem Trace: N-Queens",
    description: "N-Queens 백트래킹에서 선택/가지치기/해 발견 과정을 시각화합니다.",
    href: "/problems/backtracking-n-queens",
    ctaLabel: "N-Queens 시작",
    accentClass: "bg-pink-600 hover:bg-pink-700",
  },
];
